allowBuilds:
  '@tailwindcss/oxide': true
  core-js: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  workerd: true
